# The k8sServiceHost needs to be given separately
operator:
  replicas: 1
kubeProxyReplacement: strict
k8sServicePort: 6443
ingressController:
  enabled: true
resources:
  requests:
    cpu: 4000m
    memory: 4Gi
  limits:
    cpu: 4000m
    memory: 4Gi
