// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: demoservice.proto

package demoservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConcatenationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str1 string `protobuf:"bytes,1,opt,name=str1,proto3" json:"str1,omitempty"`
	Str2 string `protobuf:"bytes,2,opt,name=str2,proto3" json:"str2,omitempty"`
}

func (x *ConcatenationRequest) Reset() {
	*x = ConcatenationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demoservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcatenationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatenationRequest) ProtoMessage() {}

func (x *ConcatenationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demoservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatenationRequest.ProtoReflect.Descriptor instead.
func (*ConcatenationRequest) Descriptor() ([]byte, []int) {
	return file_demoservice_proto_rawDescGZIP(), []int{0}
}

func (x *ConcatenationRequest) GetStr1() string {
	if x != nil {
		return x.Str1
	}
	return ""
}

func (x *ConcatenationRequest) GetStr2() string {
	if x != nil {
		return x.Str2
	}
	return ""
}

type ConcatenatedString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *ConcatenatedString) Reset() {
	*x = ConcatenatedString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demoservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcatenatedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatenatedString) ProtoMessage() {}

func (x *ConcatenatedString) ProtoReflect() protoreflect.Message {
	mi := &file_demoservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatenatedString.ProtoReflect.Descriptor instead.
func (*ConcatenatedString) Descriptor() ([]byte, []int) {
	return file_demoservice_proto_rawDescGZIP(), []int{1}
}

func (x *ConcatenatedString) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_demoservice_proto protoreflect.FileDescriptor

var file_demoservice_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x65, 0x6d, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x65, 0x6d, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x3e, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x72, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x72, 0x31, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x72, 0x32,
	0x22, 0x26, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x32, 0x6b, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x63,
	0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x53, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x12,
	0x21, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demoservice_proto_rawDescOnce sync.Once
	file_demoservice_proto_rawDescData = file_demoservice_proto_rawDesc
)

func file_demoservice_proto_rawDescGZIP() []byte {
	file_demoservice_proto_rawDescOnce.Do(func() {
		file_demoservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_demoservice_proto_rawDescData)
	})
	return file_demoservice_proto_rawDescData
}

var file_demoservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demoservice_proto_goTypes = []interface{}{
	(*ConcatenationRequest)(nil), // 0: demoservice.ConcatenationRequest
	(*ConcatenatedString)(nil),   // 1: demoservice.ConcatenatedString
}
var file_demoservice_proto_depIdxs = []int32{
	0, // 0: demoservice.ConcatenationService.Concatenate:input_type -> demoservice.ConcatenationRequest
	1, // 1: demoservice.ConcatenationService.Concatenate:output_type -> demoservice.ConcatenatedString
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demoservice_proto_init() }
func file_demoservice_proto_init() {
	if File_demoservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demoservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConcatenationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demoservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConcatenatedString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demoservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demoservice_proto_goTypes,
		DependencyIndexes: file_demoservice_proto_depIdxs,
		MessageInfos:      file_demoservice_proto_msgTypes,
	}.Build()
	File_demoservice_proto = out.File
	file_demoservice_proto_rawDesc = nil
	file_demoservice_proto_goTypes = nil
	file_demoservice_proto_depIdxs = nil
}
