apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortioclient
  namespace: fortio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadgenerator
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: main
        image: fortio/fortio:1.38.0
        resources:
          requests:
            cpu: 4000m
            memory: 4000Mi
          limits:
            cpu: 4000m
            memory: 4000Mi
        volumeMounts:
        - mountPath: /var/lib/fortio
          name: fortio-results-volume
        - mountPath: /var/lib/access-logs
          name: fortio-access-logs-volume
      - name: shell
        image: alpine:3.16.2
        command: ["/bin/sleep"]
        args: ["1000d"]
        volumeMounts:
        - mountPath: /var/lib/fortio
          name: fortio-results-volume
        - mountPath: /var/lib/access-logs
          name: fortio-access-logs-volume
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
      volumes:
      - name: fortio-results-volume
        emptyDir: {}
      - name: fortio-access-logs-volume
        emptyDir: {}
